/*
 * Copyright Michael D. Vinci
 * michaeldvinci | coned_miro
 */
package jquelle;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.UnsupportedFlavorException;
import java.awt.dnd.DnDConstants;
import java.awt.dnd.DropTarget;
import java.awt.dnd.DropTargetDropEvent;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;

/**
 *
 * @author michaeldvinci
 */
public class Main extends javax.swing.JFrame {

    static JTextField addressField;
    static public String path;
    RepoManager repoMan1;
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    String dndPath;
    private JFrame packageFrame = new JFrame();
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        
        File f = new File("C:\\Windows\\System32\\bash.exe");
        File g = new File("C:\\Windows\\SysWOW64\\bash.exe");
        if((f.exists() && !f.isDirectory()) || (g.exists() && !g.isDirectory())) { 
            // do something
        } else {
            JOptionPane.showMessageDialog(null, "JQuelle requires Bash for Windows. Please Install and restart!");
            System.exit(0);
        }
        
        repoMan1 = new RepoManager();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        createDeb = new javax.swing.JButton();
        manageRepo = new javax.swing.JButton();
        createPackage = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        createDeb.setText("Create .deb");
        createDeb.setActionCommand("openFolder");
        createDeb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createDebActionPerformed(evt);
            }
        });

        manageRepo.setText("Manage Repo");
        manageRepo.setActionCommand("openFolder");
        manageRepo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                manageRepoActionPerformed(evt);
            }
        });

        createPackage.setText("Packages.bz2");
        createPackage.setActionCommand("openFolder");
        createPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPackageActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(createDeb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(manageRepo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createPackage, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(createPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createDeb, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(manageRepo, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void createDebActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createDebActionPerformed
        //selectFolder.setVisible(true);
        JFileChooser chooser = new JFileChooser();
        chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = chooser.showOpenDialog(null);
        switch (result) {
        case JFileChooser.APPROVE_OPTION:
            System.out.println("Approve (Open or Save) was clicked");
            path = chooser.getSelectedFile().getAbsolutePath();
            if (checkControl(path) == true) {
                System.out.println("Windows Path: " + path);
                path = path.replaceAll(":","");
                path = path.replace("\\", "/");
                path = "/mnt/c/" + path.substring(2,path.length());
                //selectF.setVisible(false);
                System.out.println("Bash Path: " + path);
                System.out.println("");
                String path2 = path;
                try {
                    PackageCreation.createPackage(path2);
                } catch (InterruptedException | IOException | NullPointerException ex) {
                    System.out.println(ex);
                }
                break;
            } else if (checkControl(path) == false) {
                JOptionPane.showMessageDialog(null, "Directory does not contain the required \\DEBIAN\\control file! Please choose again.");
                break;
            }
        case JFileChooser.CANCEL_OPTION:
            break;
        case JFileChooser.ERROR_OPTION:
            System.out.println("Error");
            break;
        }
    }//GEN-LAST:event_createDebActionPerformed

    private void manageRepoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_manageRepoActionPerformed
        //repoMan1.setDefaultCloseOperation(RepoManager.DISPOSE_ON_CLOSE);
        //repoMan1.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        //repoMan1.setVisible(true);
        loadDND();
        
        
        
    }//GEN-LAST:event_manageRepoActionPerformed

    private void createPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createPackageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_createPackageActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Main().setVisible(true);
        });
    }
    
    public boolean checkControl(String path) {
        boolean fileThere = false;
        
        File h = new File(path + "\\DEBIAN\\control");
        fileThere = h.exists() && !h.isDirectory();
        return fileThere;
    }
    
    public String loadDND() {
        
        outPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        model = new DefaultListModel();
        outList = new javax.swing.JList<>(model);
        createPackages = new javax.swing.JButton();
        packBack = new javax.swing.JButton();

        outPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));

        javax.swing.GroupLayout outPanelLayout = new javax.swing.GroupLayout(outPanel);
        outPanel.setLayout(outPanelLayout);
        outPanel.setDropTarget(new DropTarget() {
            @Override
            public synchronized void drop(DropTargetDropEvent evt) {
                try {
                    evt.acceptDrop(DnDConstants.ACTION_COPY);
                    List<File> droppedFiles = (List<File>) evt
                            .getTransferable().getTransferData(
                                    DataFlavor.javaFileListFlavor);
                    droppedFiles.forEach((file) -> {
                        dndPath = file.getAbsolutePath();
                        
                        model.addElement(dndPath + "\n");
                        System.out.println(model);
                    });
                } catch (UnsupportedFlavorException | IOException ex) {
                }
            }
        });
        outPanelLayout.setHorizontalGroup(
            outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        outPanelLayout.setVerticalGroup(
            outPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 134, Short.MAX_VALUE)
        );
        
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Drop File Here");

        jScrollPane2.setViewportView(outList);
        
        createPackages.setText("Create Packages.bz2");
        createPackages.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createPackagesActionPerformed(evt);
            }
        });

        packBack.setText("<");
        packBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                packBackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(outPanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(packBack)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(createPackages, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(packBack, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(outPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(createPackages, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
        
        createDeb.setVisible(false);
        manageRepo.setVisible(false);
        createPackage.setVisible(false);
        
        return dndPath;
    }
    
    private void createPackagesActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
    } 
    
    private void packBackActionPerformed(java.awt.event.ActionEvent evt) {                                         
        jLabel1.setVisible(false);
        jScrollPane2.setVisible(false);
        outList.setVisible(false);
        outPanel.setVisible(false);
        packBack.setVisible(false);
        
        initComponents();
    } 

    private DefaultListModel model;
    private javax.swing.JButton createPackages;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> outList;
    private javax.swing.JPanel outPanel;
    private javax.swing.JButton packBack;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createDeb;
    private javax.swing.JButton createPackage;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JButton manageRepo;
    // End of variables declaration//GEN-END:variables
}
